#Email Configuration
email.emailAddress=speech.mailing@gmail.com
email.emailPassword=twkfakoreejvzfwk

#DataBase Configuration
hibernate.connection.url=jdbc:postgresql://localhost:5432/speechdb
hibernate.connection.username=userspeech
hibernate.connection.password=0QjWJ?3KXIzA