email.emailAddress=speech.mailing@gmail.com
email.emailPassword=twkfakoreejvzfwk

hibernate.connection.url=jdbc:postgresql://192.168.1.103:5432/speechdb
hibernate.connection.username=userspeech
hibernate.connection.password=0QjWJ?3KXIzA