-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.channel_types
(
    channel_type_id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    channel_type_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT channel_types_pkey PRIMARY KEY (channel_type_id),
    CONSTRAINT channel_types_channel_type_name_key UNIQUE (channel_type_name)
);

CREATE TABLE IF NOT EXISTS public.channel_user
(
    channel_user_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    channel_id integer NOT NULL,
    background_image bytea,
    visible_name_chat character varying(50) COLLATE pg_catalog."default",
    visible_logo_chat bytea,
    status_of_the_interlocutor character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT channel_user_pkey PRIMARY KEY (channel_user_id),
    CONSTRAINT channel_user_user_id_channel_id_key UNIQUE (user_id, channel_id)
);

CREATE TABLE IF NOT EXISTS public.channels
(
    channel_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    channel_name character varying(50) COLLATE pg_catalog."default",
    channel_photo bytea,
    channel_count_user integer NOT NULL,
    channel_type_id smallint NOT NULL DEFAULT 3,
    channel_name_unique character varying COLLATE pg_catalog."default" NOT NULL,
    disable_sharing boolean NOT NULL DEFAULT false,
    owner_id integer,
    CONSTRAINT channels_pkey PRIMARY KEY (channel_id),
    CONSTRAINT channels_channel_name_unique_key UNIQUE (channel_name_unique)
);

CREATE TABLE IF NOT EXISTS public.hidden_channel_user
(
    hidden_channel_user_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    hidden_channel_id integer,
    hidden_user_id integer,
    CONSTRAINT hidden_channel_user_pkey PRIMARY KEY (hidden_channel_user_id),
    CONSTRAINT hidden_channel_user_hidden_channel_id_hidden_user_id_key UNIQUE (hidden_channel_id, hidden_user_id)
);

CREATE TABLE IF NOT EXISTS public.message_content
(
    message_content_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    message_content_bytes bytea NOT NULL,
    message_content_file_name character varying COLLATE pg_catalog."default",
    message_id bigint NOT NULL,
    CONSTRAINT message_content_pkey PRIMARY KEY (message_content_id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    message_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    message_datetime timestamp without time zone NOT NULL DEFAULT now(),
    channel_user_id bigint NOT NULL,
    message_status character varying(30) COLLATE pg_catalog."default" DEFAULT 'отправлено'::character varying,
    deleted_by_users bigint[] DEFAULT ARRAY[]::bigint[],
    modified_message boolean DEFAULT false,
    message_id_reply_to bigint,
    pin_message boolean DEFAULT false,
    forwarded_from bigint,
    message_string bytea,
    id_channel_invitations integer,
    CONSTRAINT messages_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email_user bytea NOT NULL,
    visible_name_user character varying(20) COLLATE pg_catalog."default",
    name_user character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password_user bytea NOT NULL,
    birthday_user bytea NOT NULL,
    user_photo bytea,
    user_status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'не в сети'::character varying,
    unique_identity_computer text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user__pkey PRIMARY KEY (id_user),
    CONSTRAINT user__email_user_key UNIQUE (email_user),
    CONSTRAINT user__name_user_key UNIQUE (name_user)
);

CREATE TABLE IF NOT EXISTS public.users_in_silent_mode
(
    users_in_silent_mode_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    channel_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT users_in_silent_mode_pkey PRIMARY KEY (users_in_silent_mode_id),
    CONSTRAINT users_in_silent_mode_channel_id_user_id_key UNIQUE (channel_id, user_id)
);

ALTER TABLE IF EXISTS public.channel_user
    ADD CONSTRAINT channel_user_channel_id_fkey FOREIGN KEY (channel_id)
    REFERENCES public.channels (channel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.channel_user
    ADD CONSTRAINT channel_user_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.channels
    ADD CONSTRAINT channels_channel_type_id_fkey FOREIGN KEY (channel_type_id)
    REFERENCES public.channel_types (channel_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.channels
    ADD CONSTRAINT channels_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hidden_channel_user
    ADD CONSTRAINT hidden_channel_user_hidden_channel_id_fkey FOREIGN KEY (hidden_channel_id)
    REFERENCES public.channels (channel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hidden_channel_user
    ADD CONSTRAINT hidden_channel_user_hidden_user_id_fkey FOREIGN KEY (hidden_user_id)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.message_content
    ADD CONSTRAINT message_content_message_id_fkey FOREIGN KEY (message_id)
    REFERENCES public.messages (message_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_channel_user_id_fkey FOREIGN KEY (channel_user_id)
    REFERENCES public.channel_user (channel_user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_id_channel_invitations_fkey FOREIGN KEY (id_channel_invitations)
    REFERENCES public.channels (channel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users_in_silent_mode
    ADD CONSTRAINT users_in_silent_mode_channel_id_fkey FOREIGN KEY (channel_id)
    REFERENCES public.channels (channel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users_in_silent_mode
    ADD CONSTRAINT users_in_silent_mode_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;