#Email Configuration
email.emailAddress=speech.mailing@gmail.com
email.emailPassword=twkfakoreejvzfwk

#DataBase Configuration
database.URL=jdbc:postgresql://localhost:5432/speechdb
database.userName=userspeech
database.userPassword=0QjWJ?3KXIzA